config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  #root to: 'travels#index'

  get 'travels/filter', to: 'travels#filter'
  get 'travels/random', to: 'travels#random'

  resources :users

  resources :travels do
    member do
      post 'add_to_favorites'
    end
  end

  resources :travels do
    resources :reviews
  end

  resources :travels

  resource :session, only: %i[new create destroy]

  get "/pages/:page" => "pages#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :travel
end

app/models/travel.rb
class Travel < ApplicationRecord
  mount_uploader :city_image, CityImageUploader

  has_many :user_travels
  has_many :users, through: :user_travels
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :user_travels
  has_many :travels, through: :user_travels
  has_many :reviews

  validates :email, presence: true, uniqueness: true
  validates :login, presence: true, uniqueness: true

end

app/models/user_travel.rb
class UserTravel < ApplicationRecord
  belongs_to :user
  belongs_to :travel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  private
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
      @travel = Travel.find(params[:travel_id])
      @review = @travel.reviews.build(review_params)
      @review.user = current_user

      if @review.save
        redirect_to @travel, notice: 'Отзыв успешно добавлен.'
      else
        render 'travels/show'
      end
  end
  def index
    @review= Review.all
  end
  def show
    @review = Review.find(params[:id])
  end
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to root_path, notice: 'Отзыв успешно удален.'
  end
  def edit
    @review = Review.find(params[:id])
  end


  private
  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user_params = params.require(:session)

    user = User.find_by(login: user_params[:login])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: 'Вы вошли в аккаунт.'
    else
      flash.now[:alert] = 'Неправильный логин или пароль'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта.'
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def new
    @travel = Travel.new
  end

  def create
    @travel = Travel.new(travel_params)

    if @travel.save
      redirect_to travels_path, notice: 'Travel успешно создан.'
    end
  end
  def index
    @travel= Travel.all
  end

  def show
    @travel = Travel.find(params[:id])
    @reviews = @travel.reviews
  end

  def destroy
    @travel = Travel.find(params[:id])
    @travel.destroy
    redirect_to root_path, notice: 'Travel успешно удален.'
  end
  def edit
    @travel = Travel.find(params[:id])
  end
  def update
    @travel = Travel.find(params[:id])

    if @travel.update(travel_params)
      redirect_to travel_path, notice: 'Данные travel обновлены.'
    end
  end
  def filter

  end

  def random
    # Пример обработки параметров фильтрации
    climate_filter = params[:climate] || []
    location_filter = params[:location] || []
    popularity_filter = params[:popularity] || []

    # Применение фильтров к модели Travel
    travels = Travel.all
    travels = apply_climate_filter(travels, climate_filter)
    travels = apply_water_filter(travels, location_filter)
    travels = apply_mount_filter(travels, location_filter)
    travels = apply_popularity_filter(travels, popularity_filter)

    # Выбор случайной записи из отфильтрованного списка
    redirect_to travels.sample

    # Перенаправление на страницу с выбранной записью
  end

  def add_to_favorites
    @travel = Travel.find(params[:id])
    current_user.travels << @travel
    redirect_to @travel, notice: 'Успешно добавлено в избранное.'
  end

  private

  def apply_climate_filter(travels, climate_filter)
    # Пример применения фильтра климата
    if climate_filter.include?("hot")
      travels = travels.where(climate: "Жарко")
    elsif climate_filter.include?("warm")
      travels = travels.where(climate: "Тепло")
    elsif climate_filter.include?("cold")
      travels = travels.where(climate: "Холодно")
    end
    travels
  end

  def apply_water_filter(travels, location_filter)
    return travels if location_filter.nil?

      if location_filter.include?("by_sea")
        travels = travels.where(iswater: 1)
      else
        travels
      end
    travels
    end

  def apply_mount_filter(travels, location_filter)
    return travels if location_filter.nil?

    if location_filter.include?("by_mountain")
      travels = travels.where(ismount: 1)
    else
      travels
    end
    travels
  end

  def apply_popularity_filter(travels, popularity_filter)
    # Пример применения фильтра популярности
    if popularity_filter.include?("do_popular")
      travels = travels.where(ispopular: 1)
    elsif popularity_filter.include?("not_popular")
    travels = travels.where(ispopular: 0)
    elsif popularity_filter.include?("not_important")
      travels
    end
    travels
  end


  def travel_params
    params.require(:travel).permit(
      :country, :city, :climate, :iswater, :ismount, :ispopular, :description, :todo, :city_image
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_path, notice: 'Пользователь успешно зарегистрирован.'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'
      render :new
    end
  end
  def index
    @user= User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'Аккаунт успешно удален.'
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path, notice: 'Данные пользователя обновлены.'
    else
      flash.now[:alert] = 'При попытке обновить данные возникли ошибки'
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :name, :email, :login, :password, :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="">
<head>
  <title>Diploma</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
    <div class = "navbar-main">
      <div class="navbar-title">
        <p><%=link_to 'Travel', root_path %></p>
      </div>
      <div class = "navbar">
      <p><%= link_to 'Все направления', url_for(controller: 'travels', action: 'index'), class: 'title-smm mr navbar-white' %></p>
      <p><%= link_to 'Выбрать подходящее', url_for(controller: 'travels', action: 'filter'), class: 'title-smm mr-lg navbar-white' %></p>

      <% if current_user.present? %>
        <%= link_to "@#{current_user.login}",current_user, class: 'ml-lg mr-sm title-sm navbar-white' %>
        <%= button_to 'Выйти', session_path, method: :delete, class: 'button button-main' %>
      <% else %>
        <%= link_to 'Вход', new_session_path, class: 'button button-main' %>
        <%= link_to 'Регистрация', new_user_path, class: 'button button-main' %>
      <% end %>
      </div>
    </div>
  <%if flash[:notice].present? %>
    <p class = "mb mt message message-notice"><%=flash[:notice] %></p>

  <%elsif flash[:alert].present? %>
    <p class = "mb mt message message-alert"><%=flash[:alert] %></p>
  <% end %>

  <%= yield %>

  <div class="mt-xxl footer-title">
    <p><%=link_to 'Travel', root_path %></p>
  </div>

  <div class = "footer">
    <p class = "text-center">&copy; Mikhail Konovalov 2024 </p>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<div class = "wrapper">
  <h1 class = "title-lg mb text-bold text-center t ">О нас</h1>
</div>

app/views/pages/contact.html.erb
<div class = "wrapper">
  <h1 class = "title-lg mb text-bold text-center t ">Напиши мне!</h1>
</div>

app/views/pages/gallery.html.erb
<div class = "wrapper">
  <h1 class = "title-lg mb text-bold text-center t ">Можешь расслабиться и полюбоваться прекрасными фотографиями!</h1>
</div>

app/views/pages/home.html.erb
<div class="ml-lg text-white">
  <p class="mt-xxl title-lg mb text-bold text-center helvetica">Добро пожаловать на сайт для искателей приключений!</p>

  <div class="verdana text-bold mt-xxl">
    <p class="title mt-xxl mb">ОТБРОСЬ СЕРЫЕ БУДНИ </p>
    <p class="title-xxl mt mb">ПУТЕШЕСТВУЙ!</p>
  </div>

  <div class="helvetica">
  <p class="title-sm mb-xxl ">Ищете вдохновение для следующего отпуска? Мой сайт идеально для этого подходит.<br> Каждый найдет для себя персональное предложение,<br> основанное на ваших собственных предпочтениях.
  </p>
  </div>
  <div class="helvetica text-bold title-sm mt-lg">
    <p class="title mb ">Начни свое путешествие прямо сейчас!</p>
    <div class="flex">
      <p><%= link_to 'Посмотреть все направления', url_for(controller: 'travels', action: 'index'), class: 'button button-main mr' %>ИЛИ </p>
      <p><%= link_to 'Выбрать подходящее', url_for(controller: 'travels', action: 'filter'), class: 'button button-main ml mb-xxl' %></p>
    </div>
  </div>
</div>

app/views/travels/edit.html.erb
<div class = "container">
  <h2 class = "title text-bold">Редактирования пользователя</h2>

  <div class = "mt">
    <%= form_with model: @travel, data: {turbo: false} do |form| %>
      <p class = "mt"><%= form.label :country, 'Введите country' %> </p>
      <p><%= form.text_field :country, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :city, 'Введите city' %> </p>
      <p><%= form.text_field :city, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :climate, 'Введите climate' %> </p>
      <p><%= form.text_field :climate, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :iswater, 'Введите iswater' %> </p>
      <p><%= form.text_field :iswater, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :iswmount, 'Введите ismount' %> </p>
      <p><%= form.text_field :ismount, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :ispopular, 'Введите ispopular' %> </p>
      <p><%= form.text_field :ispopular, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :description, 'Введите descr' %> </p>
      <p><%= form.text_area :description, class: 'form-text-area' %> </p>

      <p class = "mt"><%= form.label :todo, 'Введите todo' %> </p>
      <p><%= form.text_area :todo, class: 'form-text-area' %> </p>

      <p class = "mt"><%= form.label :city_image, 'Введите city_image' %> </p>
      <p><%= form.file_field :city_image, class: 'form-file-field' %> </p>

      <p class = "mt-lg link">
        <%= form.submit 'Сохранить', class: 'button button-main' %>
        <span class = "text-sm">или <%= link_to 'Вернуться в ЛК', :back %></span>
      </p>

    <%end %>
  </div>
</div>

app/views/travels/filter.html.erb
<%= form_with(url: travels_random_path, method: :get, local: true, html: { class: "travel-form" }) do |form| %>
  <div class="travel-section">
    <h2 class="section-title">Климат</h2>
    <div class="checkbox-group">
      <%= form.label :climate, "Жарко", class: 'checkbox-label' %>
      <%= form.radio_button :climate, "hot", class: 'checkbox-input' %><br>
      <%= form.label :climate, "Тепло", class: 'checkbox-label mr-sm' %>
      <%= form.radio_button :climate, "warm", class: 'checkbox-input' %>
      <%= form.label :climate, "Холодно", class: 'checkbox-label' %>
      <%= form.radio_button :climate, "cold", class: 'checkbox-input' %>
      <%= form.label :climate, "Не важно", class: 'checkbox-label' %>
      <%= form.radio_button :climate, "not_important", class: 'checkbox-input' %>
    </div>
  </div>

  <div class="travel-section">
    <h2 class="section-title">Расположение</h2>
    <div class="checkbox-group">
      <%= form.label :location, "У моря", class: 'checkbox-label mb-sm' %>
      <%= form.check_box :location, { multiple: true }, "by_sea", class: 'checkbox-input' %>
      <%= form.label :location, "У гор", class: 'checkbox-label mb-sm' %>
      <%= form.check_box :location, { multiple: true }, "by_mountain", class: 'checkbox-input' %>
      <%= form.label :location, "Не важно", class: 'checkbox-label mb-sm' %>
      <%= form.check_box :location, { multiple: true }, "not_important", class: 'checkbox-input' %>
    </div>
  </div>

  <div class="travel-section">
    <h2 class="section-title">Популярность</h2>
    <div class="checkbox-group">
      <%= form.label :popularity, "Популярное", class: 'checkbox-label' %>
      <%= form.radio_button :popularity, "do_popular", class: 'checkbox-input' %>
      <%= form.label :popularity, "Непопулярное", class: 'checkbox-label' %>
      <%= form.radio_button :popularity, "not_popular", class: 'checkbox-input' %>
      <%= form.label :popularity, "Не важно", class: 'checkbox-label' %>
      <%= form.radio_button :popularity, "not_important", class: 'checkbox-input' %>
    </div>
  </div>

  <%= form.submit "Показать", class: 'submit-button' %>
<% end %>

app/views/travels/index.html.erb
<div class="wrapper-y">
  <% @travel.each do |travel| %>
  <p class = "mt-lg mb-sm link text-center title-lg link-black"><%= link_to "#{travel.city}", travel_path(travel.id) %></p>
  <div class="wrapper mt-lg mb-lg">
    <div class = "container mt-lg mb-lg mr-lg">
      <p class = "text-center title mt-lg mb-sm"><%= travel.country %></p>
      <p class = "text-center title-sm mb"><%= travel.city%></p>
      <p class = "text-center title-sm">Климат:
        <% if travel.climate == 'Жарко' %>
          <%= 'Жарко' %>
        <% elsif travel.climate == 'Тепло' %>
          <%= 'Тепло' %>
        <% elsif travel.climate == 'Холодно' %>
          <%= 'Холодно' %>
        <% end %></p>
      <p class = "text-center title-sm">
        <% if travel.iswater? %>
          <%= 'Около моря ✅' %>
        <% else %>
          <%='Около моря ❌' %>
        <%end %></p>
      <p class = "text-center title-sm">
        <% if travel.ismount? %>
          <%= 'Около гор ✅' %>
        <% else %>
          <%='Около гор ❌' %>
        <%end %></p>
      <p class = "text-center title-sm">
        <% if travel.ispopular? %>
          <%= 'Популярно ✅' %>
        <% else %>
          <%='Популярно ❌' %>
        <%end %></p>
    </div>

    <div class = "container-desc mt-lg ml-lg mb-lg">
      <p class = "text-center title-sm"><%= travel.description %></p>
    </div>
  </div>
    <p class = "text-center"><%= image_tag travel.city_image.url, class: 'img mb' if travel.city_image? %></p>

  <% if current_user.present? %>
    <%= form_with(url: add_to_favorites_travel_path(travel), method: :post) do |form| %>
      <%= form.submit "Добавить в избранное", class: 'submit-button' %>
    <% end %>
  <% end %>


  <% end %>
</div>

app/views/travels/new.html.erb
<div class="container">
  <h2 class="title">Travel create</h2>

  <div class="mt">
    <%=form_with model: @travel, data: {turbo: false} do |form| %>
      <p class = "mt"><%= form.label :country, 'Введите country' %> </p>
      <p><%= form.text_field :country, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :city, 'Введите city' %> </p>
      <p><%= form.text_field :city, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :climate, 'Введите climate' %> </p>
      <p><%= form.text_field :climate, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :iswater, 'Введите iswater' %> </p>
      <p><%= form.text_field :iswater, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :iswmount, 'Введите ismount' %> </p>
      <p><%= form.text_field :ismount, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :ispopular, 'Введите ispopular' %> </p>
      <p><%= form.text_field :ispopular, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :description, 'Введите descr' %> </p>
      <p><%= form.text_area :description, class: 'form-text-area' %> </p>

      <p class = "mt"><%= form.label :todo, 'Введите todo' %> </p>
      <p><%= form.text_area :todo, class: 'form-text-area' %> </p>

      <p class = "mt"><%= form.label :city_image, 'Введите city_image' %> </p>
      <p><%= form.file_field :city_image, class: 'form-file-field' %> </p>



      <p class = "mt-lg"><%= form.submit 'Save', class: 'button button-main' %></p>
    <% end %>
  </div>
</div>

app/views/travels/random.html.erb
<div class = "container"> РАНДОМ
  <h2 class = "mb text-bold text-center">Travel</h2>
  <p class = "text-center">Country: <%= @travel.country %></p>
  <p class = "text-center">City: <%= @travel.city%></p>
  <p class = "text-center">Climate: <%=@travel.climate %></p>
  <p class = "text-center">IsWater: <%= @travel.iswater %></p>
  <p class = "text-center">IsMount: <%= @travel.ismount %></p>
  <p class = "text-center">IsPopular: <%= @travel.ispopular %></p>
  <p class = "text-center">Desc: <%= @travel.description %></p>
  <p class = "text-center">Photo: <%= @travel.city_image %></p>
  <p class = "text-center"><%= image_tag @travel.city_image.url, class: 'img-container' if @travel.city_image? %></p>
</div>
<div class="mt-sm mb-sm">
  <%= button_to 'Изменить данные профиля', edit_travel_path(@travel), method: :get, class: 'button button-main' %>
</div>
<div>
  <%=button_to 'Delete', @travel, method: :delete, class: 'button button-main' %>
</div>

app/views/travels/show.html.erb
<div class="wrapper-y">
  <div class="wrapper mt-lg">
  <div class = "container mt-lg mb-lg mr">
    <p class = "text-center title mb-sm mt-lg"><%= @travel.country %></p>
    <p class = "text-center title-sm mb"><%= @travel.city%></p>
    <p class = "text-center title-sm">Климат:
      <% if @travel.climate == 'Жарко' %>
          <%= 'Жарко' %>
        <% elsif @travel.climate == 'Тепло' %>
          <%= 'Тепло' %>
        <% elsif @travel.climate == 'Холодно' %>
          <%= 'Холодно' %>
        <% end %></p>
    <p class = "text-center title-sm">
      <% if @travel.iswater? %>
        <%= 'Около моря ✅' %>
      <% else %>
        <%='Около моря ❌' %>
      <%end %></p>
    <p class = "text-center title-sm">
      <% if @travel.ismount? %>
        <%= 'Около гор ✅' %>
      <% else %>
        <%='Около гор ❌' %>
      <%end %></p>
    <p class = "text-center title-sm">
      <% if @travel.ispopular? %>
        <%= 'Популярно ✅' %>
      <% else %>
        <%='Популярно ❌' %>
      <%end %></p>
  </div>

    <div class = "container-desc mt-lg ml-lg mb-lg">
    <p class = "text-center title-sm"><%= @travel.description %></p>
    </div>
</div>

  <div class = "container-desc mt-lg ml-lg mb-lg">
    <p class="text-bold text-center title-sm mb-sm helvetica">5 вещей, которые нужно сделать в этом месте: </p>
    <ul class="todo-list">
      <% @travel.todo.split("\n").each do |item| %>
        <li class="title-sm"><%= item  %></li>
      <% end %>
    </ul>
  </div>


<% if current_user.present? %>
  <%= form_with(url: add_to_favorites_travel_path(@travel), method: :post) do |form| %>
    <%= form.submit "Добавить в избранное", class: 'submit-button' %>
  <% end %>
<% end %>

<p class = "text-center"><%= image_tag @travel.city_image.url, class: 'mb mt img' if @travel.city_image? %></p>

<div class = "mt-lg">
<% if @reviews.any? %>
      <ul>
        <% @reviews.each do |review| %>
          <div class = "container-review mb">
          <li>
            <strong>Пользователь:</strong> <%= review.user.name %><br>
            <strong>Оценка:</strong> <%= review.rating %><br>
            <strong>Комментарий:</strong> <%= review.comment %><br>
          </li>
          </div>
        <% end %>
      </ul>
<% end %>

  <div class = "container-review">
    <p class="text-center text-bold mb">Были здесь? Поделитесь своими впечатлениями!</p>
    <%= form_with(model: [@travel, @travel.reviews.build], url: travel_reviews_path(@travel)) do |form| %>
      <%= form.label :rating, 'Оценка: ' %>
      <%= form.number_field :rating %><br>

      <%= form.label :comment, 'Комментарий: ' %>
      <%= form.text_area :comment, class: 'form-text-area'%>

      <%= form.submit 'Добавить отзыв', class: 'submit-button' %>
    <% end %>
  </div>
  </div>
</div>
<div class="mt-sm mb-sm">
  <%= button_to 'Изменить данные профиля', edit_travel_path(@travel), method: :get, class: 'button button-main' %>
</div>
<div>
  <%=button_to 'Delete', @travel, method: :delete, class: 'button button-main' %>
</div>

app/views/users/edit.html.erb
<div class = "mt-xxl text-center">
<div class = "container">
  <h2 class = "title text-bold">Редактирования пользователя</h2>

  <% if @user.errors.any? %>
    <div class = "mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class = "mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class = "mt">
    <%= form_with model: @user, data: {turbo: false} do |form| %>
      <p class = "mt"><%= form.label :name, 'Введите имя' %> </p>
      <p><%= form.text_field :name, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :email, 'Введите электронную почту' %> </p>
      <p><%= form.text_field :email, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :login, 'Введите логин' %> </p>
      <p><%= form.text_field :login, class: 'form-text-field' %> </p>

      <p class = "mt-lg title-sm">Если не хотите менять пароль - оставьет следующие поля пустыми</p>
      <p class = "mt"><%= form.label :password, 'Введите пароль' %> </p>
      <p><%= form.password_field :password, class: 'form-text-field' %> </p>

      <p class = "mt"><%= form.label :password_confirmation, 'Повторите пароль' %> </p>
      <p><%= form.password_field :password_confirmation, class: 'form-text-field' %> </p>

      <p class = "mt-lg link">
        <%= form.submit 'Сохранить', class: 'button button-main' %>
        <span class = "text-sm">или <%= link_to 'Вернуться в ЛК', :back %></span>
      </p>

    <%end %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<h1>Список пользователей</h1>
  <% @user.each do |user| %>
  <p class = "mb-sm"><%= link_to "User#{user.id}", user_path(user.id) %></p>
  <% end %>

app/views/users/new.html.erb
<div class="wrapper text-center">
  <div class="container mt-lg">
    <h2 class="title">Регистрация</h2>

    <% if @user.errors.any? %>
      <div class = "mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class = "mb-sm text-red"><%= message %></p>
      <% end %>
      </div>
    <% end %>

    <div class="mt">
      <%=form_with model: @user, data: {turbo: false} do |form| %>
        <p class = "mt"><%= form.label :name, 'Введите имя' %> </p>
        <p><%= form.text_field :name, class: 'form-text-field' %> </p>

        <p class = "mt"><%= form.label :email, 'Введите электронную почту' %> </p>
        <p><%= form.text_field :email, class: 'form-text-field' %> </p>

        <p class = "mt"><%= form.label :login, 'Введите логин' %> </p>
        <p><%= form.text_field :login, class: 'form-text-field' %> </p>

        <p class = "mt"><%= form.label :password, 'Введите пароль' %> </p>
        <p><%= form.password_field :password, class: 'form-text-field' %> </p>

        <p class = "mt"><%= form.label :password_confirmation, 'Повторите пароль' %> </p>
        <p><%= form.password_field :password_confirmation, class: 'form-text-field' %> </p>

        <p class = "mt-lg"><%= form.submit 'Зарегистрироваться', class: 'submit-button' %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class = "mt-xxl text-center">
  <div class = "container mt-lg">
    <h2 class = "mb text-bold text-center title-lg helvetica">Личный кабинет</h2>
    <p class = "text-center title">Имя: <%= @user.name %></p>
    <p class = "text-center title">Email: <%= @user.email%></p>
    <p class = "text-center title">Логин: <%= @user.login %></p>
    <div class="mt-sm mb-sm">
      <%= button_to 'Изменить данные профиля', edit_user_path(@user), method: :get, class: 'submit-button' %>
    </div>
    <p class = "text-center text-bold title mt-lg mb-sm"> Избранное: </p>
    <div>
      <% current_user.travels.each do |travel| %>
        <p class="verdana title-sm"><%= link_to travel.city, travel_path(travel), class:'text-center mb-sm' %></p>
      <% end %>
    </div>
  </div>
</div>
<div>
  <%=button_to 'Удалить профиль', user_path(@user), method: :delete, class: 'mt-xxl button button-main' %>
</div>